/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.PeliculaData;
import Controlador.ProyeccionData;
import Controlador.SalaData;
import Modelo.Pelicula;
import Modelo.Proyeccion;
import Modelo.Sala;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Familia
 */
public class Pagina10 extends javax.swing.JPanel {

    /**
     * Creates new form Pagina1
     */
    private ProyeccionData prod;
    private SalaData sd;
    private PeliculaData pd;

    private Sala sala;
    private Pelicula pelicula;
    private LocalDate fecha;
    private LocalTime horaInicio;
    private LocalTime horaFin;

    public Pagina10() {
        initComponents();

        this.sd = new SalaData();
        this.pd = new PeliculaData();
        this.prod = new ProyeccionData();

        jbBorrar.setEnabled(false);
        jbBorrar.setBackground(new Color(117, 21, 41));
        UIManager.put("Button.disabledText", Color.BLACK);

        cargarComboSala();
        cargarComboPelicula();
        jdcFecha.setMinSelectableDate(new Date());
        cargarComboHora();
        JTextFieldDateEditor editor = (JTextFieldDateEditor) jdcFecha.getDateEditor();
        editor.setEditable(false);
    }

    public Pagina10(Sala sala, Pelicula pelicula, LocalDate fecha, LocalTime horaInicio, LocalTime horaFin) {
        initComponents();
        this.sala = sala;
        this.pelicula = pelicula;
        this.fecha = fecha;
        this.horaInicio = horaInicio;
        this.horaFin = horaFin;

        this.sd = new SalaData();
        this.pd = new PeliculaData();
        this.prod = new ProyeccionData();

        cargarComboSala();
        cargarComboPelicula();
        jdcFecha.setMinSelectableDate(new Date());
        cargarComboHora();
        cambiarPropiedadesElementosBorrar();

    }

    private void cargarComboSala() {
        for (Sala x : sd.obtenerSalas()) {

            jcbSala.addItem(x);
        }
    }

    private void cargarComboPelicula() {
        for (Pelicula x : pd.obtenerPeliculas()) {

            jcbPelicula.addItem(x);
        }
    }

    private void cargarComboHora() {

        jcbHora1.removeAllItems();

        List<String> lista = new ArrayList<>();
        lista.add("16:00");
        lista.add("20:00");

        for (String x : lista) {

            jcbHora1.addItem(x);

        }
    }

    private void calcularHoraFin() {

        LocalTime tiempo1 = LocalTime.parse((String) jcbHora1.getSelectedItem());

        int hora1 = tiempo1.getHour() + 3;
        int minuto1 = tiempo1.getMinute() + 30;

        jtfHora2.setText(hora1 + ":" + minuto1);
    }

    private void limpiarCampos() {

        jcbSala.setSelectedIndex(0);
        jcbPelicula.setSelectedIndex(0);
        jdcFecha.setDate(null);
        jcbHora1.setSelectedIndex(0);
    }

    private void cargarDatosAlActualizar() {

        jcbSala.setSelectedItem(sala);
        jcbPelicula.setSelectedItem(pelicula);
        jdcFecha.setDate(java.sql.Date.valueOf(fecha));
        jcbHora1.setSelectedItem(horaInicio);
    }

    private void cambiarPropiedadesElementosBorrar() {
        jbGuardar.setEnabled(false);

        jcbSala.setEnabled(false);
        jcbPelicula.setEnabled(false);
        jcbHora1.setEnabled(false);
        jdcFecha.setEnabled(false);

        cargarDatosAlActualizar();

        UIManager.put("ComboBox.disabledForeground", Color.BLACK);
        UIManager.put("Button.disabledText", Color.BLACK);
        ((JTextFieldDateEditor) jdcFecha.getDateEditor()).setDisabledTextColor(Color.BLACK);

        jbGuardar.setBackground(new Color(117, 21, 41));

    }

    private void cambiarPropiedadesElementosLimpiar() {
        jbGuardar.setEnabled(true);

        jcbSala.setEnabled(true);
        jcbPelicula.setEnabled(true);
        jcbHora1.setEnabled(true);
        jdcFecha.setEnabled(true);

        jbGuardar.setBackground(new Color(235, 42, 83));

        jbBorrar.setEnabled(false);
        jbBorrar.setBackground(new Color(117, 21, 41));
        UIManager.put("Button.disabledText", Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBackgroud = new javax.swing.JPanel();
        jpContenedor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbGuardar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jcbPelicula = new javax.swing.JComboBox<>();
        jcbSala = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jtfHora2 = new javax.swing.JTextField();
        jcbHora1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jpBackgroud.setBackground(new java.awt.Color(32, 30, 45));
        jpBackgroud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpContenedor.setBackground(new java.awt.Color(32, 30, 45));
        jpContenedor.setPreferredSize(new java.awt.Dimension(1000, 530));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Formulario Proyeccion");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sala:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pelicula:");

        jbGuardar.setBackground(new java.awt.Color(235, 42, 83));
        jbGuardar.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jbGuardar.setText("Guardar");
        jbGuardar.setBorder(null);
        jbGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbBorrar.setBackground(new java.awt.Color(235, 42, 83));
        jbBorrar.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbBorrar.setForeground(new java.awt.Color(255, 255, 255));
        jbBorrar.setText("Borrar");
        jbBorrar.setBorder(null);
        jbBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbLimpiar.setBackground(new java.awt.Color(235, 42, 83));
        jbLimpiar.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jbLimpiar.setText("Limpiar");
        jbLimpiar.setBorder(null);
        jbLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jbSalir.setBackground(new java.awt.Color(235, 42, 83));
        jbSalir.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbSalir.setText("Salir");
        jbSalir.setBorder(null);
        jbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jcbPelicula.setBackground(new java.awt.Color(255, 255, 255));
        jcbPelicula.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jcbPelicula.setForeground(new java.awt.Color(0, 0, 0));
        jcbPelicula.setMaximumRowCount(3);
        jcbPelicula.setBorder(null);

        jcbSala.setBackground(new java.awt.Color(255, 255, 255));
        jcbSala.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jcbSala.setForeground(new java.awt.Color(0, 0, 0));
        jcbSala.setMaximumRowCount(3);
        jcbSala.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hora Inicio:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Hora Fin:");

        jdcFecha.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jdcFecha.setPreferredSize(new java.awt.Dimension(230, 30));

        jtfHora2.setEditable(false);
        jtfHora2.setBackground(new java.awt.Color(255, 255, 255));
        jtfHora2.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jtfHora2.setForeground(new java.awt.Color(0, 0, 0));
        jtfHora2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 5, 1, 5, new java.awt.Color(255, 255, 255)));

        jcbHora1.setBackground(new java.awt.Color(255, 255, 255));
        jcbHora1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jcbHora1.setForeground(new java.awt.Color(0, 0, 0));
        jcbHora1.setMaximumRowCount(3);
        jcbHora1.setBorder(null);
        jcbHora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHora1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpContenedorLayout = new javax.swing.GroupLayout(jpContenedor);
        jpContenedor.setLayout(jpContenedorLayout);
        jpContenedorLayout.setHorizontalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContenedorLayout.createSequentialGroup()
                .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpContenedorLayout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbSala, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jpContenedorLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpContenedorLayout.createSequentialGroup()
                                .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jpContenedorLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(52, 52, 52))
                            .addGroup(jpContenedorLayout.createSequentialGroup()
                                .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)))
                        .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpContenedorLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(25, 25, 25)
                                .addComponent(jtfHora2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpContenedorLayout.createSequentialGroup()
                                .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(178, 178, 178))
        );
        jpContenedorLayout.setVerticalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContenedorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(51, 51, 51)
                .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(42, 42, 42)
                .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpContenedorLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)))
                    .addGroup(jpContenedorLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jtfHora2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jpBackgroud.add(jpContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 530));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Logo.png"))); // NOI18N
        jpBackgroud.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 172, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BOLETERIA");
        jpBackgroud.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 221, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBackgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBackgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbHora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHora1ActionPerformed
        calcularHoraFin();
    }//GEN-LAST:event_jcbHora1ActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        int valor;

        if (jdcFecha.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Rellene todo los campos");
        } else {

            Sala sala1 = (Sala) jcbSala.getSelectedItem();
            Pelicula peli1 = (Pelicula) jcbPelicula.getSelectedItem();
            Date input = jdcFecha.getDate();
            LocalDate fecha1 = input.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalTime hora1 = LocalTime.parse((String) jcbHora1.getSelectedItem());
            LocalTime hora2 = LocalTime.parse(jtfHora2.getText());

            if (fecha1.equals(LocalDate.now()) && LocalTime.now().compareTo(hora1) == 1) {

                JOptionPane.showMessageDialog(this, "La proyeccion esta fuera de horario");
            } else {

                Proyeccion proyeccion1 = new Proyeccion(sala1, peli1, fecha1, hora1, hora2);
                prod.guardarProyeccion(proyeccion1);

            }

        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        cambiarPropiedadesElementosLimpiar();
        limpiarCampos();
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        Proyeccion proyeccion = prod.obtenerProyeccionXPeliculaXSalaXHoraXfecha(pelicula.getIdPelicula(), sala.getIdSala(), horaInicio, fecha);

        prod.BorrarProyeccion(proyeccion);
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        jpContenedor.setVisible(false);
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<String> jcbHora1;
    private javax.swing.JComboBox<Pelicula> jcbPelicula;
    private javax.swing.JComboBox<Sala> jcbSala;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JPanel jpBackgroud;
    private javax.swing.JPanel jpContenedor;
    private javax.swing.JTextField jtfHora2;
    // End of variables declaration//GEN-END:variables
}
